Repository FRONTENDBOOTCAMP-11th/Jakudacque, pull requests merged in 2024-12, with the labels that each got.

#12 ✨ feat: routes 초기 설정 #10
  src/routes.jsx
Labels: feature(개선 요청)

#15 ✨ feat: 라우터 경로 변경 및 파일 추가 #13
  src/components/layout/Category.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/pages/admin/index.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/product/Edit.jsx
  src/pages/admin/product/List.jsx
  src/pages/admin/product/New.jsx
  src/pages/product/Cart.jsx
  src/pages/product/List.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
  src/routes.jsx
Labels: feature(개선 요청)

#16 Feature/kim/#14 sample data
  api/dbinit-sample/jakudacque/data.js
Labels: p2

#17 ✨ feat: 카테고리 컴포넌트 UI
  package-lock.json
  src/App.jsx
  src/components/layout/Category.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/pages/admin/index.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/product/Edit.jsx
  src/pages/admin/product/List.jsx
  src/pages/admin/product/New.jsx
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청), P1

#19 ✨ feat: 푸터 컴포넌트 퍼블리싱 #7
  src/components/layout/Footer.jsx
Labels: feature(개선 요청)

#21 [FEATURE] 상품 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/components/Product.jsx
Labels: feature(개선 요청), P1

#22 [FEATURE] 메인홈 퍼블리싱
  package-lock.json
  package.json
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  src/components/Product.jsx
  src/pages/index.jsx
Labels: feature(개선 요청), P1

#24 [FEATURE] 관리자 페이지 상품 리스트 추가
  package-lock.json
  package.json
  src/components/AdminSearchBar.jsx
  src/components/AdminTable.jsx
  src/components/Pagenation.jsx
  src/components/Spinner.jsx
  src/components/layout/AdminLayout.jsx
  src/components/layout/Header.jsx
  src/hooks/useAxiosInstance.js
  src/hooks/useQueryStr.js
  src/main.jsx
  src/pages/admin/product/List.jsx
  src/routes.jsx
  src/zustand/userStore.js
  tailwind.config.js
Labels: feature(개선 요청), P1

#28 [FEATURE] 로그인, 회원가입 페이지 퍼블리싱
  src/pages/user/.gitkeep
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청), P1

#30 [FEATURE] 어드민 홈
  api/dbinit-sample/jakudacque/data.js
  src/components/AdminSideMenu.jsx
  src/components/Pagenation.jsx
  src/components/Spinner.jsx
  src/components/layout/AdminLayout.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/pages/admin/index.jsx
  src/pages/admin/product/List.jsx
Labels: feature(개선 요청), P1

#32 [FEATURE] 장바구니 페이지 퍼블리싱
  src/pages/product/.gitkeep
  src/pages/product/Cart.jsx
Labels: feature(개선 요청), P1

#35 [FEATURE] 상품페이지 데이터 연결과 페이지네이션, 검색 페이지 퍼블리싱, 검색기능
  api/dbinit-sample/jakudacque/data.js
  src/components/AdminSideMenu.jsx
  src/components/AdminTable.jsx
  src/components/layout/AdminLayout.jsx
  src/components/layout/Header.jsx
  src/hooks/useAxiosInstance.js
  src/pages/admin/index.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/product/List.jsx
  src/pages/product/List.jsx
  src/pages/product/Search.jsx
  src/routes.jsx
  src/zustand/codeStore.js
Labels: feature(개선 요청)

#36 [FEATURE] 관리자 주문 목록 페이지 추가
  src/hooks/useAxiosInstance.js
  src/pages/admin/order/List.jsx
  src/pages/admin/product/List.jsx
Labels: feature(개선 요청), P1
