Repository FRONTENDBOOTCAMP-11th/Jakudacque, pull requests merged in 2025-02, with the labels that each got.

#212 [DOCUMENTATION] README 파일 추가
  README.md
Labels: documentation(문서화)

#213 [FEATURE] 모달, 카운터, 찜 store 전역 상태에서 제거
  src/components/AddAddressModal.jsx
  src/components/AddressModal.jsx
  src/components/CartModal.jsx
  src/components/Product.jsx
  src/components/ProductList.jsx
  src/components/RestoreWishList.jsx
  src/components/layout/index.jsx
  src/hooks/useAddCart.js
  src/hooks/useAddress.js
  src/hooks/useHandleWish.js
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/user/MyPage.jsx
  src/zustand/AddAddressModalState.js
  src/zustand/AddressModalState.js
  src/zustand/AddressStore.js
  src/zustand/cartModalState.js
  src/zustand/counter.js
  src/zustand/wishState.js
Labels: refactor(리팩토링)

#215 [FEATURE] Seachstore로 헤더와 검색페이지 검색바를 전역으로 관리하는 것에서 url에 쿼리 남겨서 하는 방식으로 바꾸기
  src/components/layout/Header.jsx
  src/hooks/useChannelTalk.js
  src/pages/product/Search.jsx
  src/zustand/searchStore.js
Labels: refactor(리팩토링)

#216 [FEATURE] 컴포넌트 분리, 상품 상세페이지 카테고리 쿼리스트링 보존
  src/components/AddAddressModal.jsx
  src/components/InputField.jsx
  src/components/Product.jsx
  src/hooks/useAddCart.js
  src/pages/index.jsx
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/user/MyPage.jsx
Labels: feature(개선 요청), refactor(리팩토링)
