Repository FRONTENDBOOTCAMP-11th/Jakudacque, pull requests merged in 2025-01, with the labels that each got.

#39 [FEATURE] 공통 컴포넌트 - 탑 버튼
  src/components/layout/TopButton.jsx
  src/components/layout/index.jsx
  src/pages/product/List.jsx
Labels: feature(개선 요청)

#41 [FEATURE] 어드민 상품 수정/추가 페이지 작업
  package-lock.json
  package.json
  src/components/AdminSideMenu.jsx
  src/components/Button.jsx
  src/components/ImageUploader.jsx
  src/components/InputGroup.jsx
  src/components/InputSelect.jsx
  src/components/InputToggle.jsx
  src/components/Pagenation.jsx
  src/components/QuillEditor.jsx
  src/components/layout/AdminLayout.jsx
  src/constants/admin.js
  src/pages/admin/order/List.jsx
  src/pages/admin/product/Edit.jsx
  src/pages/admin/product/List.jsx
  src/pages/admin/product/New.jsx
  src/routes.jsx
Labels: feature(개선 요청), P1

#44 [FEATURE] Toast 알링창 추가
  src/App.jsx
  src/components/Toast.jsx
  src/pages/product/Cart.jsx
Labels: feature(개선 요청), P1

#48 [FEATURE] 리스트, 검색 페이지 현재 페이지 정보 보여주기(상품 개수, 카테고리, 검색) , 반응형 수정
  src/pages/product/List.jsx
  src/pages/product/Search.jsx
Labels: feature(개선 요청)

#51 [FEATURE] 메인홈, 로그인, 회원가입, 장바구니 스타일 수정
  public/kakao_login.png
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청), P1

#53 [FEATURE] 어드민 주문 상세 페이지 추가
  api/dbinit-sample/jakudacque/data.js
  src/components/InputGroup.jsx
  src/pages/admin/order/Edit.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/product/List.jsx
  src/routes.jsx
Labels: feature(개선 요청), P1

#54 [FEATURE] 카테고리 정보 가져오기, 필터링, 페이지 이동 기능구현
  src/components/layout/Category.jsx
  src/pages/product/List.jsx
Labels: feature(개선 요청)

#55 [FEATURE] 마이페이지 퍼블리싱
  src/components/Product.jsx
  src/pages/user/MyPage.jsx
  src/routes.jsx
Labels: feature(개선 요청)

#58 [FEATURE] 상품 상세, 푸터 스타일 수정
  src/components/layout/Footer.jsx
  src/pages/product/Detail.jsx
Labels: feature(개선 요청)

#60 [FEATURE] 헤더 컴포넌트 개선
  src/components/layout/AdminLayout.jsx
  src/components/layout/Header.jsx
Labels: feature(개선 요청)

#61 [FEATURE] 토스트 컴포넌트 개선
  src/components/Button.jsx
  src/components/InputGroup.jsx
  src/components/Toast.jsx
  src/pages/admin/order/Edit.jsx
  src/pages/admin/product/Edit.jsx
  src/pages/admin/product/List.jsx
Labels: feature(개선 요청)

#63 [BUGFIX] 버튼 컴포넌트에 배경색이 적용되지 않는 문제
  src/components/Button.jsx
Labels: bug(버그)

#65 [FEATURE] 상품 정렬 기능 추가
  src/pages/product/List.jsx
Labels: feature(개선 요청)

#68 [FEATURE] 이메일 로그인, 회원가입 기능 추가
  src/components/InputError.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청), P1

#70 [FEATURE] 상품 상세 조회 기능, 구매 기능, 찜 기능 추가
  src/pages/product/Detail.jsx
  src/zustand/counter.js
  src/zustand/wishState.js
Labels: feature(개선 요청)

#75 [FEATURE] 어드민 주문 목록 필터링 추가
  package-lock.json
  package.json
  src/components/InputSelect.jsx
  src/components/PeriodCalendar/CalendarBody.jsx
  src/components/PeriodCalendar/CalendarContainer.jsx
  src/components/PeriodCalendar/CalendarMonth.jsx
  src/components/PeriodCalendar/CalendarStyle.module.css
  src/constants/admin.js
  src/pages/admin/order/List.jsx
Labels: feature(개선 요청), p2

#77 [FEATURE] 장바구니 모달 컴포넌트 추가
  src/components/CartModal.jsx
  src/zustand/modalState.js
Labels: feature(개선 요청), P1

#79 [FEATURE] 로그인 유저 타입별 리다이렉트 처리 기능 추가
  src/pages/user/SignIn.jsx
  src/pages/user/SignInKakao.jsx
Labels: feature(개선 요청)

#81 [FEATURE] 어드민 유저 권한에 따른 분기 추가
  src/components/AdminSideMenu.jsx
  src/components/layout/AdminLayout.jsx
  src/pages/admin/master/category/List.jsx
  src/pages/admin/master/user/List.jsx
  src/pages/admin/seller/Dashboard.jsx
  src/pages/admin/seller/order/Edit.jsx
  src/pages/admin/seller/order/List.jsx
  src/pages/admin/seller/product/.gitkeep
  src/pages/admin/seller/product/Edit.jsx
  src/pages/admin/seller/product/List.jsx
  src/pages/admin/seller/product/New.jsx
  src/routes.jsx
Labels: feature(개선 요청)

#86 [REFACTOR] 관리자 유저 1명으로 일원화
  api/dbinit-sample/jakudacque/data.js
  src/components/layout/AdminLayout.jsx
  src/pages/admin/Dashboard.jsx
  src/pages/admin/category/List.jsx
  src/pages/admin/order/Edit.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/product/.gitkeep
  src/pages/admin/product/Edit.jsx
  src/pages/admin/product/List.jsx
  src/pages/admin/product/New.jsx
  src/pages/admin/user/List.jsx
  src/routes.jsx
Labels: refactor(리팩토링)

#87 [FEATURE] 로그아웃 기능 추가, 헤더 유저 상태에 따른 아이콘 변경
  src/components/layout/Header.jsx
  src/hooks/useAxiosInstance.js
  src/pages/user/MyPage.jsx
Labels: feature(개선 요청)

#88 [FEATURE] 어드민 회원관리 추가
  src/components/InputGroup.jsx
  src/components/InputSelect.jsx
  src/components/layout/Header.jsx
  src/pages/admin/order/Edit.jsx
  src/pages/admin/product/Edit.jsx
  src/pages/admin/user/List.jsx
  src/routes.jsx
Labels: feature(개선 요청)

#89 [FEATURE] 채널톡 컴포넌트와 훅 추가
  package-lock.json
  src/App.jsx
  src/components/ChannelTalk.jsx
  src/hooks/useChannelTalk.js
Labels: feature(개선 요청)

#91 [FEATURE] 찜 기능 커스텀 훅으로 추가
  src/components/RestoreWishList.jsx
  src/components/layout/index.jsx
  src/hooks/useHandleWish.js
  src/pages/product/Detail.jsx
  src/pages/user/MyPage.jsx
  src/zustand/wishState.js
Labels: feature(개선 요청), P1

#93 [FEATURE] 어드민, 로그인, 회원가입 페이지에서 채널톡버튼 안보이게 수정
  src/components/ChannelTalk.jsx
Labels: feature(개선 요청)

#95 [FEATURE] Product 컴포넌트에서 상세 페이지로 이동
  src/components/Product.jsx
Labels: feature(개선 요청)

#97 [FEATURE] 구매 기능 리팩토링 및 장바구니 추가 기능
  src/hooks/useAddCart.js
  src/hooks/useOrder.js
  src/pages/product/Detail.jsx
Labels: feature(개선 요청)

#98 [FEATURE] 마이페이지 찜 내역 조회 기능 추가 및 장바구니 추가 기능 연결
  src/components/Product.jsx
  src/hooks/useAddCart.js
  src/pages/product/Detail.jsx
  src/pages/user/MyPage.jsx
Labels: feature(개선 요청)

#99 [FEATURE] 어드민 카테고리 관리 추가
  src/components/InputGroup.jsx
  src/pages/admin/category/List.jsx
Labels: feature(개선 요청)

#101 [BUGFIX] 채널톡 컴포넌트가 페이지 전환 시 재초기화되지 않는 문제 해결
  src/components/ChannelTalk.jsx
Labels: bug(버그)

#106 [FEATURE] 탑 버튼 컴포넌트 스타일 변경
  src/components/layout/TopButton.jsx
Labels: feature(개선 요청)

#107 [FEATURE] 마이페이지 주문 조회 기능 추가
  jsconfig.json
  src/components/OrderDetail.jsx
  src/components/OrderProduct.jsx
  src/components/Product.jsx
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/user/MyPage.jsx
  src/utils/formatPrice.js
  vite.config.js
Labels: feature(개선 요청)

#109 [REFACOR] 카테고리 컴포넌트 zustand를 활용한 상태 관리
  src/components/layout/Category.jsx
  src/hooks/useAxiosInstance.js
Labels: refactor(리팩토링)

#110 [FEATURE] 찜 기능 리팩토링
  src/components/Product.jsx
  src/hooks/useHandleWish.js
  src/pages/product/Detail.jsx
  src/zustand/wishState.js
Labels: refactor(리팩토링)

#111 [FEATURE] 장바구니 페이지 구매하기 기능 추가 및 반응형 수정
  src/pages/product/Cart.jsx
Labels: feature(개선 요청)

#115 [BUGFIX] 장바구니 페이지 구매 오류
  src/pages/product/Cart.jsx
Labels: bug(버그)

#118 [FEATURE] 신상, 베스트 상품 페이지 추가
  src/pages/product/List.jsx
Labels: feature(개선 요청)

#119 [FEATURE] 회원가입 페이지 배송지, 주소 필수 항목으로 수정
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청)

#121 [FEATURE] 메인 페이지로 돌아갈 때는 카테고리 선택 상태를 초기화
  src/components/layout/Category.jsx
Labels: feature(개선 요청)

#122 [FEATURE] 마이페이지 회원 정보 수정 퍼블리싱
  src/pages/user/MyPage.jsx
Labels: feature(개선 요청)

#124 [FEATURE] 메인홈 베스트, 신제품 목록 조회 기능 추가
  src/pages/index.jsx
Labels: feature(개선 요청)

#126 [FEATURE] 배송지 필드 삭제 및 주소 name을 기본 배송지로 변경
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청)

#129 [REFACTOR] 메인홈 리팩토링
  src/pages/index.jsx
Labels: refactor(리팩토링)

#134 [FEATURE] 검색바 상태를 전역으로 관리
  src/components/layout/Header.jsx
  src/pages/product/Search.jsx
  src/zustand/searchStore.js
Labels: feature(개선 요청)

#136 [FEATURE] 로그인, 회원가입 버튼 반응형 추가
  src/constants/.gitkeep
  src/pages/admin/product/.gitkeep
  src/pages/product/Cart.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청)

#138 [FEATURE] 마이페이지 주문내역, 찜 리스트 수정
  src/components/OrderDetail.jsx
  src/components/Product.jsx
  src/pages/product/Detail.jsx
  src/pages/user/MyPage.jsx
  src/utils/formatPrice.js
Labels: feature(개선 요청)

#140 [FEATURE] 네비게이션 화살표 스타일 변경
  src/pages/index.jsx
Labels: feature(개선 요청)

#142 [BUGFIX] 카테고리 컴포넌트 뒤로가기 안되는 버그, 페이지 이동 시 채널톡이 깜빡이는 버그 해결
  src/App.jsx
  src/components/ChannelTalk.jsx
  src/components/layout/Category.jsx
  src/components/layout/index.jsx
Labels: bug(버그)

#144 [FEATURE] class 스타일 전반적으로 수정
  package.json
  src/App.jsx
  src/components/Address.jsx
  src/components/AdminSideMenu.jsx
  src/components/AdminTable.jsx
  src/components/Button.jsx
  src/components/CartModal.jsx
  src/components/ChannelTalk.jsx
  src/components/ImageUploader.jsx
  src/components/InputGroup.jsx
  src/components/InputSelect.jsx
  src/components/InputToggle.jsx
  src/components/OrderDetail.jsx
  src/components/OrderProduct.jsx
  src/components/Pagenation.jsx
  src/components/PeriodCalendar/CalendarContainer.jsx
  src/components/PeriodCalendar/CalendarStyle.module.css
  src/components/Product.jsx
  src/components/Toast.jsx
  src/components/layout/Category.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/TopButton.jsx
  src/hooks/useChannelTalk.js
  src/index.css
  src/pages/admin/category/List.jsx
  src/pages/admin/order/Edit.jsx
  src/pages/admin/order/List.jsx
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/product/Search.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
  src/zustand/searchStore.js
  tailwind.config.js
Labels: feature(개선 요청)

#145 [FEATURE] 카테고리 컴포넌트 반응형 삭제
  src/components/layout/Category.jsx
Labels: feature(개선 요청)

#146 [FEATURE] 어드민 대시보드 추가
  .gitignore
  package-lock.json
  package.json
  src/components/layout/AdminLayout.jsx
  src/components/layout/index.jsx
  src/hooks/useAxiosInstance.js
  src/hooks/useChannelTalk.js
  src/pages/admin/Dashboard.jsx
  src/pages/product/Search.jsx
  src/pages/user/SignIn.jsx
Labels: feature(개선 요청), p2

#147 [FEATURE] 버튼 스타일 통일, 장바구니 페이지 글자 크기 축소, 카카오로그인 페이지 환경변수 추가
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignInKakao.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청)

#149 Feature/cha/#38 product components
  package-lock.json
  src/components/BackButton.jsx
  src/components/ProductList.jsx
  src/pages/product/List.jsx
  src/pages/product/Search.jsx
Labels: feature(개선 요청)

#152 [BUGFIX] 상세페이지 버그 픽스
  src/hooks/useAddress.js
  src/pages/product/Detail.jsx
  src/pages/product/List.jsx
  src/pages/user/MyPage.jsx
Labels: bug(버그)

#154 [BUGFIX] 상품 리스트 페이지에서는 상품 찜, 장바구니 아이콘이 안 뜨는 거 보이게 하기
  src/components/ProductList.jsx
Labels: bug(버그)

#158 [FEATURE] 상품 상세정보 content 필드에서 가져오도록 변경
  src/pages/product/Detail.jsx
Labels: feature(개선 요청)

#163 Bugfix/kim/#162 admin order list
  src/components/layout/AdminLayout.jsx
  src/pages/admin/Dashboard.jsx
  src/pages/admin/order/List.jsx
  src/pages/admin/user/List.jsx
Labels: bug(버그)

#165 [FEATURE] 마이페이지 쿼리스트링 추가
  src/components/AddressModal.jsx
  src/components/layout/Header.jsx
  src/hooks/useAddress.js
  src/pages/user/MyPage.jsx
Labels: feature(개선 요청)

#167 [BUGFIX] 찜 기능 버그 픽스 및 QA
  src/components/Address.jsx
  src/components/Product.jsx
  src/hooks/useHandleWish.js
  src/pages/product/Detail.jsx
  src/pages/user/MyPage.jsx
Labels: bug(버그), feature(개선 요청)

#169 [FEATURE] 채널톡에서 상담하는 사람의 고객 정보(이름)이 제대로 나오게 수정
  src/components/ChannelTalk.jsx
Labels: feature(개선 요청)

#170 [FEATURE] 마이페이지 회원 정보 수정 탭 - 주소 추가 모달
  src/components/AddAddressModal.jsx
  src/components/CartModal.jsx
  src/pages/user/MyPage.jsx
  src/zustand/AddAddressModalState.js
  src/zustand/AddressStore.js
Labels: feature(개선 요청)

#172 [FEATURE] 장바구니 페이지 수정 및 카카오로그인 라우터 주소 변경
  src/components/AddressModal.jsx
  src/hooks/useCartCleanUp.js
  src/hooks/useOrder.js
  src/pages/product/Cart.jsx
  src/pages/product/Detail.jsx
  src/routes.jsx
  src/zustand/AddressModalState.js
Labels: feature(개선 요청)

#175 [BUGFIX] 제품 데이터의 id 타입과 관련된 문제
  src/components/Product.jsx
  src/pages/index.jsx
Labels: bug(버그)

#177 [FEATURE] 마이페이지 스타일 수정
  src/components/OrderProduct.jsx
  src/pages/user/MyPage.jsx
  src/zustand/wishState.js
Labels: feature(개선 요청)

#179 [BUGFIX] 구매하기 주소 전달 안되는 오류 해결 및 구매 후 주소선택 모달 안닫히는 오류 해결
  src/components/AddressModal.jsx
  src/hooks/useAddress.js
  src/hooks/useCartCleanUp.js
  src/hooks/useCartDeleteItem.js
  src/pages/product/Cart.jsx
  src/zustand/counterCart.js
Labels: bug(버그), feature(개선 요청)

#181 [BUGFIX] 카운터(수량) 초기화 되지 않는 버그 픽스
  src/pages/product/Detail.jsx
  src/zustand/counter.js
Labels: bug(버그), feature(개선 요청)

#183 [BUGFIX] 장바구니 상품 선택 안 했을 시 구매 완료되는 오류
  src/pages/product/Cart.jsx
Labels: bug(버그)

#185 [FEATURE] 모달 외부 클릭시 모달창 닫기 기능 추가
  src/components/AddAddressModal.jsx
  src/components/AddressModal.jsx
  src/components/CartModal.jsx
Labels: feature(개선 요청)

#187 [BUGFIX] 상품 리스트 페이지에서 다른 카테고리로 이동할 때는 정렬 옵션이 초기화되지 않는 버그 픽스
  src/pages/product/List.jsx
Labels: bug(버그)

#188 [FEATURE] 로그인 버튼 스타일 수정
  public/kakao_login.png
  public/kakao_symbol.png
  src/pages/index.jsx
  src/pages/product/Cart.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: feature(개선 요청)

#189 [BUGFIX] 마이페이지 배송지 초기화 되지 않는 버그
  src/components/Address.jsx
  src/pages/user/MyPage.jsx
  src/zustand/AddressStore.js
Labels: bug(버그)

#191 [BUGFIX] 마이페이지 오류 수정
  src/components/AddAddressModal.jsx
  src/pages/user/MyPage.jsx
Labels: bug(버그)

#193 [BUGFIX] 어드민 로그아웃 후 메인홈에서 카테고리가 바로 안나오는 버그 픽스
  src/components/layout/Category.jsx
  src/pages/user/SignIn.jsx
Labels: bug(버그)

#196 [BUGFIX] 카테고리 생성 후 상품이 없는 카테고리 이동할 때 무한 루프 발생
  api/dbinit-sample/jakudacque/data.js
  src/pages/product/List.jsx
Labels: bug(버그)

#198 [FEATURE] 검색어 로그 제거 및 상품 수량 기본값을 99999로 변경
  src/components/AdminTable.jsx
  src/pages/admin/product/New.jsx
Labels: p3

#203 [FEATURE] 어드민 카테고리 업데이트시 상태 최신화
  src/components/AdminSideMenu.jsx
  src/components/layout/AdminLayout.jsx
  src/components/layout/Header.jsx
  src/hooks/useAxiosInstance.js
  src/pages/admin/category/List.jsx
  src/zustand/codeStore.js
Labels: p3

#204 [BUGFIX] 메인홈 장바구니추가 모달 오류, 상품가격 proptypes 오류
  src/components/Product.jsx
  src/components/ProductList.jsx
  src/pages/index.jsx
Labels: bug(버그), feature(개선 요청)

#207 [BUGFIX] 주문 데이터에 user 필드 추가
  api/dbinit-sample/jakudacque/data.js
Labels: bug(버그)

#209 [FEATURE] 코드 저장 방식 개선 및 카테고리 업데이트 로직 수정, Category 컴포넌트 의존성 줄임.
  src/components/layout/AdminLayout.jsx
  src/components/layout/Category.jsx
  src/pages/admin/category/List.jsx
  src/zustand/codeStore.js
Labels: feature(개선 요청)
